### ISSUE TITLE
How to use with pre-existing Traefik set-up?

### ISSUE THREAD

**Issue by Spass1966** [xamanu/xmpp-server#1]
I have a pre-existing docker-compose network of services I'd like to slot your xmpp-server into. Traefik is set-up to issue ACME certificates appended to `./traefik/acme.json`. My other services don't need this cert explicitly given but it looks like `xmpp-server` sources a `./data/certs` directory.

Here's my adaptation of your declaration:
```
  prosody:
    image: xamanu/xmpp-server
    container_name: prosody
    volumes:
      - ./prosody/conf.d:/etc/prosody/conf.d
      - ./prosody/config:/var/lib/prosody/data
    ports:
      - "5222:5222" # 5222/tcp: client to server
      - "5269:5269" # 5269/tcp: server to server
      - "5280:5280" # 5280/tcp: http server
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:chat.${DOMAIN};PathPrefix:/_xmpp"
      - "traefik.port=5280"
    restart: always
```

`docker logs prosody`
```
startup             info	Hello and welcome to Prosody version 0.11.2
startup             info	Prosody is using the select backend for connection handling
portmanager         info	Activated service 's2s' on [*]:5269, [::]:5269
certmanager         error	SSL/TLS: Failed to load '/etc/prosody/certs/localhost.key': Check that the permissions allow Prosody to read this file. (for localhost)
localhost:tls       error	Error creating context for c2s: error loading private key (Permission denied)
certmanager         error	SSL/TLS: Failed to load '/etc/prosody/certs/localhost.key': Previous error (see logs), or other system error. (for localhost)
localhost:tls       error	Error creating contexts for s2sout: error loading private key (system lib)
certmanager         error	SSL/TLS: Failed to load '/etc/prosody/certs/localhost.key': Previous error (see logs), or other system error. (for localhost)
localhost:tls       error	Error creating contexts for s2sin: error loading private key (system lib)
portmanager         info	Activated service 'c2s' on [*]:5222, [::]:5222
portmanager         info	Activated service 'legacy_ssl' on no ports
```

So clearly my cert is not being provided to the container. Adding `./traefik/:/cert:ro` to mounted volumes doesn't work either because the container doesn't seem to know what to do with the acme.json file.
